num_epochs: 30
encoder_length: !!int 14
forecast_length: !!int 14
hidden_size: !!int 128
dropout: 0.2 
weight_decay: 0.0e-4 
learning_rate: 5.0e-6
device: !!int 3
model_name: HySonLab
datasources: [['simulation']]
eval_datasources : [['simulation']]
noise:
  train:
    gaussian_mean: 0
    gaussian_std: 0.0
    locations_perc: 0.0
  eval:
    gaussian_mean: 0
    gaussian_std: 0.0
    locations_perc: 0.0
num_eval_runs: !!int 1
num_train_runs: !!int 3