num_epochs: 50
encoder_length: !!int 14
forecast_length: !!int 14
d_model: !!int 64
d_hid: !!int 128
layers: !!int 4
n_heads: !!int 8
dropout: 0.2 
weight_decay: 0.0e-4 
learning_rate: 5.0e-6
device: !!int 1
model_name: TST
datasources: [['simulation']]
eval_datasources : [['simulation']]
noise:
  train:
    gaussian_mean: 0
    gaussian_std: 0.0
    locations_perc: 0.0
  eval:
    gaussian_mean: 0
    gaussian_std: 0.0
    locations_perc: 0.0
num_eval_runs: !!int 1
num_train_runs: !!int 3